### ISSUE TITLE
Docker Containers is Empty

### ISSUE THREAD

**Issue by chenhengwei1999** [valeoai/carrada_dataset#12]
Hello, after I followed the tutorial, I entered the docker container, but there was no relevant code in the container. Even, there are no files under path /home. Also, there is no carrada_dataset package in conda environment.

![image](https://user-images.githubusercontent.com/63592913/180404420-5978f053-aa63-4a71-b179-0ea7606315bb.png)

![image](https://user-images.githubusercontent.com/63592913/180404780-4081d51e-bf42-48e6-89d6-b447cbb22d6f.png)

![image](https://user-images.githubusercontent.com/63592913/180408040-ca927f7e-e867-4d27-b879-328a2abd4db1.png)

Could you please check the docker container?  Thank you a lot.

**Comment by ArthurOuaknine** [comment]
Hello.

I am sorry but I am not able to test the container for the moment.
However, I did proper tests with the container and both the dependencies and the repo were well installed. So please verify that you are in the correct container and not an empty one that you generated.

You can also generate the container itself. The DockerFile explicitly ask to install the repo at line 14 with "RUN pip install -e ./carrada_dataset".
If there is a problem with Docker or the repo, it should raise an error while building the container. If it doesn't and you still have an empty container, it means that you badly attached your container.

I hope it will help.

**Comment by chenhengwei1999** [comment]
@ArthurOuaknine
I have solved this problem now. The creation of the image was not successfully completed due to network reasons. Thank you for your reply.
