### ISSUE TITLE
bounding box

### ISSUE THREAD

**Issue by sutiankang** [valeoai/carrada_dataset#13]
Thanks for your great work.
I have a problem that how can I get bounding box coordinate in all sequences.

**Comment by ArthurOuaknine** [comment]
Hi.
The bounding box annotations are in the annotation files of the Carrada dataset folder.
You have the coordinates for each id sequence, id frame and id instance of the object.
Please have a look to the README file in the dataset folder, it may help you to better understand the structure of the files.

**Comment by sutiankang** [comment]
> Hi. The bounding box annotations are in the annotation files of the Carrada dataset folder. You have the coordinates for each id sequence, id frame and id instance of the object. Please have a look to the README file in the dataset folder, it may help you to better understand the structure of the files.

Can you provide a object detection code? Thanks.

**Comment by ArthurOuaknine** [comment]
We do not provide a baseline in object detection. You should try any object detection tutorial in your favourite DL framework.
Best.

**Comment by sutiankang** [comment]
> Hi. The bounding box annotations are in the annotation files of the Carrada dataset folder. You have the coordinates for each id sequence, id frame and id instance of the object. Please have a look to the README file in the dataset folder, it may help you to better understand the structure of the files.

I also have a question about the coordinate type of the box, such as xyxy or xywh, etc. Thanks!

**Comment by ArthurOuaknine** [comment]
The bounding box annotations are [[x1, y1], [x2, y2]]
