### ISSUE TITLE
About executing the jupyter notebook

### ISSUE THREAD

**Issue by r0hrh0** [valeoai/carrada_dataset#15]
I attempted to run the jupyter notebook with the sample annotations but it keeps throwing key errors. Is running the pipeline necessary to execute the jupyter notebook as the sample annotation are already present in it? What could be the possible issues behind the error? ps: I did run the pipelines.

**Comment by ArthurOuaknine** [comment]
Hello. 
The notebook is only used to visualize samples. Please ensure that you correctly downloaded the datasets (containing the pre-generated labels) and you wrote the correct path to access them.
