### ISSUE TITLE
Download Datasetq

### ISSUE THREAD

**Issue by Ainecop** [valeoai/carrada_dataset#16]
Hi there, I cant download the dataset from the blog. It gives the following error

![forbidden](https://github.com/valeoai/carrada_dataset/assets/131943499/2c6b1dde-cab8-4310-bc38-ac9674a9ce92)

**Comment by ArthurOuaknine** [comment]
Hello,
The access to the Carrada dataset works well, please use the following link (which is the same than on my website): [http://download.tsi.telecom-paristech.fr/Carrada/](http://download.tsi.telecom-paristech.fr/Carrada/)
If it does not work, please consider using another internet network and/or a VPN (it will work for sure from either Canada or France).
Hope this will help.
