### ISSUE TITLE
Raw ADC data of mmwave

### ISSUE THREAD

**Issue by luckyyf0517** [valeoai/carrada_dataset#17]
Hello, may I ask if it is possible to release the raw adc data of the millimeter wave radar?

This work provided me with a great dataset for the millimeter wave task, but Im looking forward to using complex signals for data analysis and learning, because in addition to the reflected intensity signal, the raw adc data also provides a phase signal in the time dimension, which is useful for time-domain learning. 

I can also use the raw adc data to perform cutomized operation such as beamforming to get better-resolution images, but only the preprocessed intensity heatmaps were available in the dataset. 

Thank you!

**Comment by ArthurOuaknine** [comment]
Hi, thanks for your interest in our work!
Unfortunately we are not able to release the raw ADC.
The rawest version of the data we can release are the 3D tensors after FFTs, which are already available.
Sorry for the inconvenience.
I would suggest to explore our other work, the [RADIal dataset](https://github.com/valeoai/RADIal) (with raw ADC), but we currently have a storage issue, the access is currently suspended for an unknown period of time. Stay tuned on the repo for more information
