### ISSUE TITLE
Configuration file .cfg for AWR1843BOOST

### ISSUE THREAD

**Issue by VladMrchd** [valeoai/carrada_dataset#18]
Hello,

I posted this in a closed issue, so I'm instead creating a new one.
Can you, by any chance, share the whole .cfg file used for the radar AWR1843BOOST configuration during the data capture?
I tried making one with the information in the article, but I didn't manage to make it work properly.

Thanks !

**Comment by ArthurOuaknine** [comment]
Hi, unfortunately we did not plan to release this configuration file at that time. We no longer have access to the set up used and I'm no longer in contact with the team who recorded the dataset.
Sorry for the inconvenience.
