### ISSUE TITLE
About the different files present in Carrada 

### ISSUE THREAD

**Issue by Ainecop** [valeoai/carrada_dataset#19]
Hi there, Where can we find description of the files present in the dataset (all including .json, .numpy etc)
For example,
labels.json
world.json 
data_seq_ref.json etc

Hoping for a reply soon. Thanks

**Comment by ArthurOuaknine** [comment]
Hi.
As mentioned in the README of this repo:
> The CARRADA dataset contains the camera images, the raw radar data and the generated annotations. A README.md file in the dataset provides details about all the files.
Best.
