### ISSUE TITLE
RAD tensor size 

### ISSUE THREAD

**Issue by previlige666** [valeoai/carrada_dataset#2]
hi! i download the database named Caradar_RAD. i found the *.npy data'size is 256x256x64. i can understand 256x64 represent range*doppler, but what about the other 256? in your view,it is angle but angle channel is nearly 8 (2T4R) 、12(3T4R) before fft. is angle fft is 256fft??? 
i would appreciate it if you reply it

**Comment by ArthurOuaknine** [comment]
Hello.
I apologise for the late answer.
The dimensions of the RAD tensors are rangeXangleXdoppler, corresponding to 256x256x64.
The angle dimension is indeed 256 after the FFT, there are redundant information in this dimension but it has been processed this way during the recordings.
I hope it will help.
