### ISSUE TITLE
Dataset not available for download

### ISSUE THREAD

**Issue by toomuch086** [valeoai/carrada_dataset#21]
Using the installation with or without Docker cannot download the carrada dataset. Can someone please provide alternative? Thanks in advance

**Comment by ArthurOuaknine** [comment]
Can you please be more precise in the type or error you are facing?
Please consider following the guidelines of this issue for downloading: https://github.com/valeoai/carrada_dataset/issues/16

**Comment by ArthurOuaknine** [comment]
Hello again.
After double checking, there is indeed an issue with the dataset storage.
I've contacted the person in charge, I hope they will be able to solve this problem soon.
I reopen the issue and will let you know asap when the dataset is available again.

**Comment by toomuch086** [comment]
Hi Arthur, thank you for looking into the issue once again. I will wait patiently. Kind regards.

**Comment by ArthurOuaknine** [comment]
The dataset is back online.
If you still have an error, please consider changing you network and/or using a VPN.

**Comment by toomuch086** [comment]
Yes, I can access the dataset now.
Thank you for resolving the problem.
