### ISSUE TITLE
Are camera pictures marked in the dataset?

### ISSUE THREAD

**Issue by wufangyi233** [valeoai/carrada_dataset#3]
Hello, author. Are camera pictures marked in the dataset? I didn't find any file to mark the camera pictures in your data. If so, could you please tell me which file it is? Thank you for your reply！

**Comment by ArthurOuaknine** [comment]
Hello.
I'm sorry but we do not provide ground truth on camera images (bounding box or segmentation mask).
The scenes are really simple, you can use a pretrained Mask-RCNN to generate the annotations as we did. It works well.

I hope it will help.
Best.
Arthur
