### ISSUE TITLE
Instances of each object

### ISSUE THREAD

**Issue by hpaul96** [valeoai/carrada_dataset#5]
Hii,
How will I know instances of each object in the image?
Where are the Instances are stored and if there is no object in the image file then what should be an Instances?

**Comment by ArthurOuaknine** [comment]
Hi.
A README is available in the compressed folder of the dataset.
It should specify the name of the files containing the annotations (.json).
There are two files with different structure, they are dictionnary if you load them with Python.
One of them is built has imbricated dictionnaries. The first key correspond the sequence name, the second to the frame name, the third to the instance ID of the object and the others for the annotations corresponding to this object.
If there is no annotated object in the frame, the third dictionnary is empty.

I hope it will help.
Best.
Arthur
