### ISSUE TITLE
How Doppler velocity is measured? 

### ISSUE THREAD

**Issue by hpaul96** [valeoai/carrada_dataset#6]
Hi,

I have observed in your Data set you have made an excel sheet called "DOAPoints" for each folder.

In the DOAPoints excel sheet, you have mentioned Doppler velocity(m/s) in one column. Can you explain how you measure velocity from your code(I can see the formula in your paper but not in your code)?

Secondly, you have also mentioned Power Receive(dB) in another column, kindly tell me what logic you use in code to measure it?

**The image file is attached for example kindly look into it***

Thank You
![DOA](https://user-images.githubusercontent.com/47212447/158447989-b3956701-7f80-4469-ba8b-2d21f4beef73.jpeg)

**Comment by ArthurOuaknine** [comment]
Hello.

First, the "Power Received" column actually corresponds to the Radar Cross Section (RCS).
Both the Doppler effect and the RCS are the radar data, their are not "computed" using code.
As a reminder, the Doppler effect is deduced from a phase shift between the transmitted and received signals. The RCS is the intensity of the recorded signal, with a log-transform in our case.

The DOA points are obtained by applied a CFAR algorithm on the raw data (range-angle and range-Doppler). This step is not provided in the code but it basically selects only the high reflections. Thus we obtain a point cloud with coordinates, Doppler and RCS.

I hope it will answer you question.
Best.
