### ISSUE TITLE
Can you disclose the specific model of the radar sensor you are using?

### ISSUE THREAD

**Issue by zhai-EE** [valeoai/carrada_dataset#9]

**Comment by ArthurOuaknine** [comment]
Hello.
The radar used is a AWR1843-BOOST from Texas Instruments.
All the available specs of the sensor we used are available in the article: https://arxiv.org/abs/2005.01456
I hope it will help. Best.

**Comment by zhai-EE** [comment]
Thank you. Would you please upload the origin radar echo data ?
I think it may be beneficial to the research of sensor fusion at signal level.

**Comment by ArthurOuaknine** [comment]
I am sorry but we are not able to release the ADC data of the dataset, only the RAD tensors are available.
If you want to access raw radar data, I suggest you to explore the RADIal dataset, recently accepted at CVPR 2022.

**Comment by ArthurOuaknine** [comment]
The repo is available here: https://github.com/valeoai/RADIal

**Comment by ZHOUYI1023** [comment]
> 

In your thesis, you mentioned the radar is AWR1843-BOOST. So can you confirm what the radar type is?

**Comment by ArthurOuaknine** [comment]
Yes you are right, my mistake, I updated my comment. Thanks for your comment.

**Comment by zhai-EE** [comment]
Thank you, that's the data that I need.

**Comment by VladMrchd** [comment]
Hello,

Can you, by any chance, share the whole .cfg file used for the radar configuration during the data capture?
I can't seem to reproduce it.

Thanks !
